In [1]:
import numpy as np

In [2]:
def QR_decomposition(A):
    Q = np.zeros_like(A)
    R = np.zeros_like(A)
    for i in range(A.shape[1]):
        dp = [np.dot(A[:, i], Q[:, j]) for j in range(i)]
        R[:i, i] = dp
        Q[:, i] = A[:, i]-sum(dp[j]*Q[:, j] for j in range(i))
        Q[:, i] = Q[:, i]/np.linalg.norm(Q[:, i])
        R[i, i] = np.dot(A[:, i], Q[:, i])
    return Q, R


In [3]:
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=float)
eps = .01
A = np.array([[1+eps, 1, 1], [1, 1, 1], [1, 1, 1+eps]])
Q, R = QR_decomposition(A)
np.linalg.det(A), Q, R, Q.T.dot(Q), Q.dot(R), A


(0.00010000000000000009,
 array([[ 5.81180069e-01, -8.13774986e-01, -2.76336273e-12],
        [ 5.75425811e-01,  4.10956368e-01, -7.07106781e-01],
        [ 5.75425811e-01,  4.10956368e-01,  7.07106781e-01]]),
 array([[1.73784349, 1.73203169, 1.73778595],
        [0.        , 0.00813775, 0.01224731],
        [0.        , 0.        , 0.00707107]]),
 array([[ 1.00000000e+00, -1.38816872e-14,  3.83133449e-14],
        [-1.38816872e-14,  1.00000000e+00,  3.42310575e-12],
        [ 3.83133449e-14,  3.42310575e-12,  1.00000000e+00]]),
 array([[1.01, 1.  , 1.  ],
        [1.  , 1.  , 1.  ],
        [1.  , 1.  , 1.01]]),
 array([[1.01, 1.  , 1.  ],
        [1.  , 1.  , 1.  ],
        [1.  , 1.  , 1.01]]))

In [4]:
np.linalg.qr(A)

(array([[-5.81180069e-01,  8.13774986e-01,  3.30836419e-17],
        [-5.75425811e-01, -4.10956368e-01, -7.07106781e-01],
        [-5.75425811e-01, -4.10956368e-01,  7.07106781e-01]]),
 array([[-1.73784349, -1.73203169, -1.73778595],
        [ 0.        , -0.00813775, -0.01224731],
        [ 0.        ,  0.        ,  0.00707107]]))