In [2]:
import numpy as np

In [3]:
A = np.matrix([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=float)

In [4]:
def QR_gram_schmidt(A):
    Q = np.zeros_like(A)
    R = np.zeros_like(A)
    for i in range(A.shape[1]):
        dp = Q[:, :i].T@A[:, i]
        R[:i, i] = dp
        Q[:, i] = A[:, i]-Q[:, :i]@dp
        Q[:, i] = Q[:, i]/np.linalg.norm(Q[:, i])
        R[i, i] = Q[:, i].T@A[:, i]
    return Q, R


In [5]:
Q, R = QR_gram_schmidt(A)
Q, R, Q.T.dot(Q), Q.dot(R), A

(matrix([[ 0.85714286, -0.39428571, -0.33142857],
         [ 0.42857143,  0.90285714,  0.03428571],
         [-0.28571429,  0.17142857, -0.94285714]]),
 matrix([[ 14.,  21., -14.],
         [  0., 175., -70.],
         [  0.,   0.,  35.]]),
 matrix([[ 1.00000000e+00, -4.18882616e-17, -3.08143533e-17],
         [-4.18882616e-17,  1.00000000e+00,  8.01852915e-17],
         [-3.08143533e-17,  8.01852915e-17,  1.00000000e+00]]),
 matrix([[ 12., -51.,   4.],
         [  6., 167., -68.],
         [ -4.,  24., -41.]]),
 matrix([[ 12., -51.,   4.],
         [  6., 167., -68.],
         [ -4.,  24., -41.]]))

In [6]:
def matrice_householder(U):
    return np.eye(U.shape[0]) - 2 * (U@U.T) / (U.T@U)

In [7]:
def QR_householder(A):
    n = A.shape[0]
    R = A.copy()
    Q = np.eye(n)
    for k in range(n):
        U = R[k:, k].copy()
        norme_U = np.linalg.norm(U)
        if U[0] != norme_U:
            U[0] -= norme_U
            S = matrice_householder(U)
            Q[:, k:] = Q[:, k:]@S
            R[k:, :] = S@R[k:, :]
    return Q, R


In [8]:
def QR_householder_recu(A):
    if A.shape[0] == 1:
        return (np.matrix([[1]]), A) if A[0, 0] > 0 else (np.matrix([[-1]]), -A)
    U = A[:, 0].copy()
    norme_U = np.linalg.norm(U)
    if U[0] != norme_U:
        U[0] -= norme_U
        Q = matrice_householder(U)
        R = Q@A
    else:
        Q = np.eye(A.shape[0])
        R = A
    Q1, R1 = QR_householder_recu(R[1:, 1:])
    Q[:, 1:] = Q[:, 1:]@Q1
    R[1:, 1:] = R1
    return Q, R


In [9]:
A = np.matrix([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=float)


In [10]:
QR_householder_recu(A)


(matrix([[ 0.85714286, -0.39428571, -0.33142857],
         [ 0.42857143,  0.90285714,  0.03428571],
         [-0.28571429,  0.17142857, -0.94285714]]),
 matrix([[ 1.40000000e+01,  2.10000000e+01, -1.40000000e+01],
         [-8.88178420e-16,  1.75000000e+02, -7.00000000e+01],
         [-2.22044605e-16,  1.81188398e-15,  3.50000000e+01]]))