In [5]:
import numpy as np


In [69]:
def QR_gram_schmidt(A):
    Q = np.zeros_like(A)
    R = np.zeros_like(A)
    for i in range(A.shape[1]):
        dp = [np.dot(A[:, i], Q[:, j]) for j in range(i)]
        R[:i, i] = dp
        Q[:, i] = A[:, i]-sum(dp[j]*Q[:, j] for j in range(i))
        Q[:, i] = Q[:, i]/np.linalg.norm(Q[:, i])
        R[i, i] = np.dot(A[:, i], Q[:, i])
    return Q, R


In [81]:
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=float)
eps = .01
A = np.array([[1+eps, 1, 1], [1, 1, 1], [1, 1, 1+eps]])
Q, R = QR_gram_schmidt(A)
np.linalg.det(A), Q, R, Q.T.dot(Q), Q.dot(R), A


(0.00010000000000000009,
 array([[ 5.81180069e-01, -8.13774986e-01, -2.76336273e-12],
        [ 5.75425811e-01,  4.10956368e-01, -7.07106781e-01],
        [ 5.75425811e-01,  4.10956368e-01,  7.07106781e-01]]),
 array([[1.73784349, 1.73203169, 1.73778595],
        [0.        , 0.00813775, 0.01224731],
        [0.        , 0.        , 0.00707107]]),
 array([[ 1.00000000e+00, -1.38816872e-14,  3.83133449e-14],
        [-1.38816872e-14,  1.00000000e+00,  3.42310575e-12],
        [ 3.83133449e-14,  3.42310575e-12,  1.00000000e+00]]),
 array([[1.01, 1.  , 1.  ],
        [1.  , 1.  , 1.  ],
        [1.  , 1.  , 1.01]]),
 array([[1.01, 1.  , 1.  ],
        [1.  , 1.  , 1.  ],
        [1.  , 1.  , 1.01]]))

In [82]:
np.linalg.qr(A)


(array([[-5.81180069e-01,  8.13774986e-01,  3.30836419e-17],
        [-5.75425811e-01, -4.10956368e-01, -7.07106781e-01],
        [-5.75425811e-01, -4.10956368e-01,  7.07106781e-01]]),
 array([[-1.73784349, -1.73203169, -1.73778595],
        [ 0.        , -0.00813775, -0.01224731],
        [ 0.        ,  0.        ,  0.00707107]]))

In [2]:
def matrice_householder(U):
    return np.eye(U.shape[0]) - 2 * (U@U.T) / (U.T@U)


In [ ]:
def QR_householder(A):
    n = A.shape[0]
    R = A.copy()
    Q = np.eye(n)
    for k in range(n):
        U = R[k:, k].copy()
        norme_U = np.linalg.norm(U)
        if U[0] != norme_U:
            U[0] -= norme_U
            S = matrice_householder(U)
            Q[:, k:] = Q[:, k:]@S
            R[k:, :] = S@R[k:, :]
    return Q, R


In [8]:
def QR_householder_recu(A):
    if A.shape[0] == 1:
        return (np.matrix([[1]]), A) if A[0, 0] > 0 else (np.matrix([[-1]]), -A)
    U = A[:, 0].copy()
    norme_U = np.linalg.norm(U)
    if U[0] != norme_U:
        U[0] -= norme_U
        Q = matrice_householder(U)
        R = Q@A
    else:
        Q = np.eye(A.shape[0])
        R = A
    Q1, R1 = QR_householder_recu(R[1:, 1:])
    Q[:, 1:] = Q[:, 1:]@Q1
    R[1:, 1:] = R1
    return Q, R


In [9]:
A = np.matrix([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=float)


In [10]:
QR_householder_recu(A)


(matrix([[ 0.85714286, -0.39428571, -0.33142857],
         [ 0.42857143,  0.90285714,  0.03428571],
         [-0.28571429,  0.17142857, -0.94285714]]),
 matrix([[ 1.40000000e+01,  2.10000000e+01, -1.40000000e+01],
         [-8.88178420e-16,  1.75000000e+02, -7.00000000e+01],
         [-2.22044605e-16,  1.81188398e-15,  3.50000000e+01]]))